### ISSUE TITLE
nginx 1.13.4 fails to build

### ISSUE THREAD

**Issue by netsafe** [pagespeed/ngx_pagespeed#1455]
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -I/usr/include/apr-1 -DNDK_SET_VAR -DNDK_UPSTREAM_LIST      -I/usr/include/apr-1       -I/usr/include/apr-1 -I/usr/include     -I/usr/include     -I/usr/include/libxml2     -DWITH_LUA -I/usr/include     -DWITH_PCRE_STUDY -DMODSEC_PCRE_MATCH_LIMIT=1500 -DMODSEC_PCRE_MATCH_LIMIT_RECURSION=1500  -DREQUEST_EARLY  -DCACHE_LUA     -DPERFORMANCE_MEASUREMENT            -DWITH_APU_CRYPTO -DWITH_REMOTE_RULES     -I/usr/local/include -DPCRE_STATIC     -DWITH_YAJL -I/usr/include/yajl     -DWITH_SSDEEP -I/usr//include  -D_GLIBCXX_USE_CXX11_ABI=0 --std=c++11  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/work/ngx_devel_kit/objs -I objs/addon/ndk -I /usr/work/modsecurity/nginx/modsecurity -I /usr/work/modsecurity/nginx/modsecurity/../../standalone -I /usr/work/modsecurity/nginx/modsecurity/../../apache2 -I /usr/work/pcre -I /usr/work/openssl-1.1.0f/.openssl/include -I objs -I src/http -I src/http/modules -I src/http/v2 -I src/http/modules/perl -I /usr/work/ngx_devel_kit/src -I /usr/work/ngx_devel_kit/src -I /usr/work/ngx_devel_kit/objs -I objs/addon/ndk -I /usr/work/ngx_pagespeed/psol/include -I /usr/work/ngx_pagespeed/psol/include/third_party/chromium/src -I /usr/work/ngx_pagespeed/psol/include/third_party/google-sparsehash/src/src -I /usr/work/ngx_pagespeed/psol/include/third_party/google-sparsehash/gen/arch/linux/x64/include -I /usr/work/ngx_pagespeed/psol/include/third_party/grpc/src/include -I /usr/work/ngx_pagespeed/psol/include/third_party/protobuf/src/src -I /usr/work/ngx_pagespeed/psol/include/third_party/re2/src -I /usr/work/ngx_pagespeed/psol/include/out/Release/obj/gen -I /usr/work/ngx_pagespeed/psol/include/out/Release/obj/gen/protoc_out/instaweb -I /usr/work/ngx_pagespeed/psol/include/third_party/apr/src/include -I /usr/work/ngx_pagespeed/psol/include/third_party/aprutil/src/include -I /usr/work/ngx_pagespeed/psol/include/third_party/apr/gen/arch/linux/x64/include -I /usr/work/ngx_pagespeed/psol/include/third_party/aprutil/gen/arch/linux/x64/include -I /usr/work/ngx_pagespeed/psol/include/url \
        -o objs/addon/src/ngx_pagespeed.o \
        /usr/work/ngx_pagespeed/src/ngx_pagespeed.cc
/usr/work/ngx_pagespeed/src/ngx_pagespeed.cc: In function ‘char* net_instaweb::{anonymous}::ps_merge_srv_conf(ngx_conf_t*, void*, void*)’:
/usr/work/ngx_pagespeed/src/ngx_pagespeed.cc:1164:53: error: ‘class net_instaweb::RewriteOptions’ has no member named ‘standby’
       if (!cfg_s->server_context->global_options()->standby()) {
                                                     ^~~~~~~
/usr/work/ngx_pagespeed/src/ngx_pagespeed.cc: In function ‘ngx_int_t net_instaweb::{anonymous}::ps_preaccess_handler(ngx_http_request_t*)’:
/usr/work/ngx_pagespeed/src/ngx_pagespeed.cc:3023:31: error: ‘ngx_http_core_try_files_phase’ was not declared in this scope
   while (ph[i + 1].checker != ngx_http_core_try_files_phase &&
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
objs/Makefile:1737: recipe for target 'objs/addon/src/ngx_pagespeed.o' failed
make[1]: *** [objs/addon/src/ngx_pagespeed.o] Error 1
make[1]: Leaving directory '/usr/work/nginx-1.13.4'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by netsafe** [comment]
a little update: patch from https://patch-diff.githubusercontent.com/raw/pagespeed/ngx_pagespeed/pull/1453.diff and net/instaweb folder from https://github.com/pagespeed/mod_pagespeed did the trick - it works!

**Comment by oschaaf** [comment]
@netsafe what commands did you run (and where did you find them)?

The following error makes me think you are building `ngx_pagespeed/master` against `mod_pagespeed/1.12.34.2`:
```
{anonymous}::ps_merge_srv_conf(ngx_conf_t*, void*, void*)’:
/usr/work/ngx_pagespeed/src/ngx_pagespeed.cc:1164:53: error: ‘class net_instaweb::RewriteOptions’ has no member named ‘standby’
if (!cfg_s->server_context->global_options()->standby()) {
```

**Comment by kronflux** [comment]
I also get the error. at first, I was getting the exact issue described in issue #1451, so I applied the fix(same diff file as @netsafe mentioned), which resulted in the
`‘class` net_instaweb::RewriteOptions’ has no member named ‘standby’
issue

I'm following a basic guide to compile nginx with pagespeed, which basically guides me to download this:
https://github.com/pagespeed/ngx_pagespeed/archive/v1.12.34.2-stable.zip
which gets extracted(in my case, to /usr/local/src), then this:
wget https://dl.google.com/dl/page-speed/psol/1.12.34.2-x64.tar.gz
extracted to the same directory

using the example ./configure options, I simply add this to the end:
--add-module=/usr/local/src/ngx_pagespeed-1.12.34.2-stable

this is the point where I get the first error, I apply the patch to the src/ngx_pagespeed.cc file, which then produces the second error.

**Comment by oschaaf** [comment]
@kronflux so when I extract https://github.com/pagespeed/ngx_pagespeed/archive/v1.12.34.2-stable.zip and open up ngx_pagespeed.cc line 1164 does not look like `if (!cfg_s->server_context->global_options()->standby()) {`.  So I am a bit confused about that..

(On the `master` branch that line does correspond with the error though: https://github.com/pagespeed/ngx_pagespeed/blob/master/src/ngx_pagespeed.cc#L1164 )

Can you point me to the url of the guide you followed? Maybe I can spot what is going on and suggest a correction there.
The official one is here: https://modpagespeed.com/doc/build_ngx_pagespeed_from_source

**Comment by kronflux** [comment]
You seem to have completely missed the part about the patch xD
The file is now changed to match the fix, the whole file is here:
https://github.com/pagespeed/ngx_pagespeed/blob/6ba8658cf9c8ea8c7f0c043483927dac905846a1/src/ngx_pagespeed.cc

**Comment by kronflux** [comment]
Actually, that is the guide I'm following(ish)
I didn't use the variable bits in the commands (NPS_RELEASE_NUMBER, etc)
I simply worked out the correct URLs and used those directly - also extracted files manually.
I skipped the bits using "scripts/format_binary_url.sh", and used the x64 link directly.

As for nginx, I've compiled it many times, so I'm going by memory, however originally I used the official compile guide for nginx.

I'm doing nothing special, except I'm manually grabbing the files.

Perhaps the patch depends on additional changes which are not present in the stable zip?

**Comment by kronflux** [comment]
ah yes. I'm just not too bright.
The patch is specifically for the current(?) branch 1.13.4, the stable release zip is 1.12.34.2

1.12.34.2 was where I was experiencing: ngx_http_core_try_files_phase’ was not declared in this scope
assumedly there's no easy way to use the fix for 1.13.4 with this release, so I'll just either have to switch to the latest branch, or wait until the next stable release.

**Comment by kronflux** [comment]
Found the issue!
https://github.com/pagespeed/mod_pagespeed/pull/1482
This is not present in the current PSOL download.

**Comment by oschaaf** [comment]
@kronflux that's correct, pagespeed/mod_pagespeed#1482 isn't included in `1.12.34.2-stable`

**Comment by kronflux** [comment]
Would replacing the instaweb folder from the psol download with the one from mod_pagespeed be sufficient? or would this more likely lead to additional issues?

I suppose one could simply add the standby code to the current psol file.
Just trying to find the best way to use the stable release files, without having to wait for a new PSOL release.

**Comment by Dukemasters** [comment]
Same problem, only path to openssl is different 
root/addons/nginx-1.13.4
ngx_cache_purge-2.3 \
ngx_slowfs_cache-1.10 \
ngx_pagespeed-1.12.34.2-stable
ngx_cache_purge-2.3 \
ngx_slowfs_cache-1.10 \
ngx_coolkit-0.2 \
ngx_headers-more-0.32
Ubuntu 16.04.3 with Plesk Onyx 17.5.3 by 1and1. Normal Plesk built-in nginx 1.11.10.
OpenSSL is here, --with-openssl=**/usr/src/openssl-1.0.2l** \ 
not in /usr/local/src/
Greets

**Comment by kronflux** [comment]
I think something was wrong with my build environment. I was able to get it to build on a fresh Ubuntu 16.10 installation perfectly using the patch mentioned previously.

All is good here with 1.13.4 and latest stable pagespeed(with patch applied)

**Comment by oschaaf** [comment]
Fixed via https://github.com/pagespeed/ngx_pagespeed/pull/1453

**Comment by LuckySB** [comment]
not fixed for me (
centos 6.8
psol from https://dl.google.com/dl/page-speed/psol/1.12.34.2-x64.tar.gz

 git log
commit ef3899515e40fc4fd7dd553fdef0048e937db7f4

`                ngx_pagespeed-1.12.34.2-stable/src/ngx_rewrite_driver_factory.cc
ngx_pagespeed-1.12.34.2-stable/src/ngx_pagespeed.cc: In function 'char* net_instaweb::{anonymous}::ps_merge_srv_conf(ngx_conf_t*, void*, void*)':
ngx_pagespeed-1.12.34.2-stable/src/ngx_pagespeed.cc:1165:53: error: 'class net_instaweb::RewriteOptions' has no member named 'standby'
       if (!cfg_s->server_context->global_options()->standby()) {
                                                     ^
make[1]: *** [objs/addon/src/ngx_pagespeed.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/root/rpmbuild/BUILD/nginx-module-pagespeed-1.13.4'
make: *** [modules] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.6H95Ck (%build)
`

**Comment by oschaaf** [comment]
@LuckySB ef38995 is the head of the current ngx_pagespeed master. 

That should have been f3c64ca8a251f05f228ad32947d7c68c89308f6a (a.k.a. tag v1.12.34.2-stable)

**Comment by kevin25** [comment]
Still got the same issue thought the psol is updated

`objs/Makefile:1429: recipe for target 'objs/addon/src/ngx_pagespeed.o' failed
make[1]: *** [objs/addon/src/ngx_pagespeed.o] Error 1
make[1]: Leaving directory '/usr/local/src/nginx-1.13.5'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2`
