### ISSUE TITLE
ngx_pagespeed-1.7.30.4-beta doesn't work with nginx 1.5.13

### ISSUE THREAD

**Issue by runningman84** [pagespeed/ngx_pagespeed#660]
Is this a known problem?

```
../ngx_pagespeed-1.7.30.4-beta//src/ngx_pagespeed.cc: In function 'ngx_int_t net_instaweb::{anonymous}::in_place::ps_in_place_check_header_filter(ngx_http_request_t*)':
../ngx_pagespeed-1.7.30.4-beta//src/ngx_pagespeed.cc:2186:24: error: no matching function for call to 'net_instaweb::InPlaceResourceRecorder::InPlaceResourceRecorder(net_instaweb::RequestContextPtr, GoogleString&, net_instaweb::RequestHeaders*, bool, int64, int64, net_instaweb::HTTPCache*, net_instaweb::Statistics*, net_instaweb::MessageHandler*&)'
../ngx_pagespeed-1.7.30.4-beta//src/ngx_pagespeed.cc:2186:24: note: candidates are:
../ngx_pagespeed-1.7.30.4-beta//psol/include/net/instaweb/system/public/in_place_resource_recorder.h:133:3: note: net_instaweb::InPlaceResourceRecorder::InPlaceResourceRecorder(const net_instaweb::InPlaceResourceRecorder&)
../ngx_pagespeed-1.7.30.4-beta//psol/include/net/instaweb/system/public/in_place_resource_recorder.h:133:3: note:   candidate expects 1 argument, 9 provided
../ngx_pagespeed-1.7.30.4-beta//psol/include/net/instaweb/system/public/in_place_resource_recorder.h:45:3: note: net_instaweb::InPlaceResourceRecorder::InPlaceResourceRecorder(base::StringPiece, net_instaweb::RequestHeaders*, bool, int, int, net_instaweb::HTTPCache*, net_instaweb::Statistics*, net_instaweb::MessageHandler*)
../ngx_pagespeed-1.7.30.4-beta//psol/include/net/instaweb/system/public/in_place_resource_recorder.h:45:3: note:   candidate expects 8 arguments, 9 provided
../ngx_pagespeed-1.7.30.4-beta//src/ngx_pagespeed.cc: In function 'ngx_int_t net_instaweb::{anonymous}::in_place::ps_in_place_body_filter(ngx_http_request_t*, ngx_chain_t*)':
../ngx_pagespeed-1.7.30.4-beta//src/ngx_pagespeed.cc:2243:9: error: 'kPreliminaryHeaders' is not a member of 'net_instaweb::InPlaceResourceRecorder'
make[3]: *** [objs/addon/src/ngx_pagespeed.o] Error 1
make[3]: Leaving directory `/usr/src/nginx-1.5.13'
make[2]: *** [build] Error 2
make[2]: Leaving directory `/usr/src/nginx-1.5.13'
dh_auto_build: make -j1 returned exit code 2
make[1]: *** [override_dh_auto_build] Error 2
make[1]: Leaving directory `/usr/src/nginx-1.5.13'
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```
