### PR TITLE
Fix compiling issue with older nginx

### PR DESCRIPTION
**Pull request by PikachuEXE**
I got issue compiling with nginx 1.13.3 with master
since the enum `NGX_HTTP_PRECONTENT_PHASE` is only added after `1.13.4`

Error message was:
```
/usr/local/src/ngx_pagespeed/src/ngx_pagespeed.cc: In function ‘ngx_int_t net_instaweb::{anonymous}::ps_init(ngx_conf_t*)’:
/usr/local/src/ngx_pagespeed/src/ngx_pagespeed.cc:3089:17: error: ‘NGX_HTTP_PRECONTENT_PHASE’ was not declared in this scope
     int phase = NGX_HTTP_PRECONTENT_PHASE;
                 ^
```

Related change was introduced in https://github.com/pagespeed/ngx_pagespeed/pull/1453

### CODE REVIEW

**Comment by oschaaf** [comment]
Ugh, nice catch, thank you! 
LGTM

**Comment by PikachuEXE** [comment]
Build passed

**Comment by PikachuEXE** [comment]
Just a reminder for reviewers :)

**Comment by PikachuEXE** [comment]
Will a new version be released?
Or do we need to install it from source?

**Comment by oschaaf** [comment]
@PikachuEXE we are working on a point release (see https://github.com/pagespeed/ngx_pagespeed/issues/1451#issuecomment-331876667)
