### ISSUE TITLE
Unable to build 1.6.29.7 with GCC 4.8

### ISSUE THREAD

**Issue by jc00ke** [pagespeed/ngx_pagespeed#553]
```
$> ./configure --add-module=../ngx_pagespeed-release-1.6.29.7-beta
$> make
...
...
...
                -o objs/addon/src/log_message_handler.o \
                ../ngx_pagespeed-release-1.6.29.7-beta/src/log_message_handler.cc
In file included from ../ngx_pagespeed-release-1.6.29.7-beta/psol/include/third_party/chromium/src/base/logging.h:14:0,
                 from ../ngx_pagespeed-release-1.6.29.7-beta/src/log_message_handler.cc:30:
../ngx_pagespeed-release-1.6.29.7-beta/psol/include/third_party/chromium/src/base/basictypes.h: In function ‘Dest bit_cast(const Source&)’:
../ngx_pagespeed-release-1.6.29.7-beta/psol/include/third_party/chromium/src/base/basictypes.h:318:16: error: typedef ‘VerifySizesAreEqual’ locally defined but not used [-Werror=unused-local-typedefs]
   typedef char VerifySizesAreEqual [sizeof(Dest) == sizeof(Source) ? 1 : -1];
                ^
cc1plus: all warnings being treated as errors
make[1]: *** [objs/addon/src/log_message_handler.o] Error 1
make[1]: Leaving directory `/home/jesse/projects/nginx-buildpack/tmp/nginx-1.5.6'
make: *** [build] Error 2
```

I'm trying to build on Ubuntu 13.10.
Please let me know what other info might be helpful to add.

Thanks!
