### ISSUE TITLE
Error during compiled on  Centos of release-1.9.32.1-beta

### ISSUE THREAD

**Issue by phodal** [pagespeed/ngx_pagespeed#803]
it is the details 

```
-lpthread -lcrypt -lstdc++ ../ngx_pagespeed-release-1.9.32.1-beta/psol/lib/Release/linux/ia32/pagespeed_automatic.a -lrt -pthread -lm -lpcre -lssl -lcrypto -ldl -lz
cobjs/addon/src/ngx_pagespeed.o: In function `net_instaweb::(anonymous namespace)::ps_pre_init(ngx_conf_s*)':
/home/temp/lnmp1.0/nginx-1.7.5/../ngx_pagespeed-release-1.9.32.1-beta/src/ngx_pagespeed.cc:2964: undefined reference to `net_instaweb::g_gzip_setter'
/home/temp/lnmp1.0/nginx-1.7.5/../ngx_pagespeed-release-1.9.32.1-beta/src/ngx_pagespeed.cc:2964: undefined reference to `net_instaweb::NgxGZipSetter::Init(ngx_conf_s*)'
objs/addon/src/ngx_pagespeed.o: In function `net_instaweb::(anonymous namespace)::ps_configure(ngx_conf_s*, net_instaweb::NgxRewriteOptions**, net_instaweb::MessageHandler*, net_instaweb::RewriteOptions::OptionScope)':
/home/temp/lnmp1.0/nginx-1.7.5/../ngx_pagespeed-release-1.9.32.1-beta/src/ngx_pagespeed.cc:625: undefined reference to `net_instaweb::g_gzip_setter'
/home/temp/lnmp1.0/nginx-1.7.5/../ngx_pagespeed-release-1.9.32.1-beta/src/ngx_pagespeed.cc:625: undefined reference to `net_instaweb::NgxGZipSetter::EnableGZipForLocation(ngx_conf_s*)'
/home/temp/lnmp1.0/nginx-1.7.5/../ngx_pagespeed-release-1.9.32.1-beta/src/ngx_pagespeed.cc:627: undefined reference to `net_instaweb::g_gzip_setter'
/home/temp/lnmp1.0/nginx-1.7.5/../ngx_pagespeed-release-1.9.32.1-beta/src/ngx_pagespeed.cc:627: undefined reference to `net_instaweb::NgxGZipSetter::SetGZipForLocation(ngx_conf_s*, bool)'
/home/temp/lnmp1.0/nginx-1.7.5/../ngx_pagespeed-release-1.9.32.1-beta/src/ngx_pagespeed.cc:632: undefined reference to `net_instaweb::g_gzip_setter'
/home/temp/lnmp1.0/nginx-1.7.5/../ngx_pagespeed-release-1.9.32.1-beta/src/ngx_pagespeed.cc:632: undefined reference to `net_instaweb::NgxGZipSetter::SetGZipForLocation(ngx_conf_s*, bool)'
/home/temp/lnmp1.0/nginx-1.7.5/../ngx_pagespeed-release-1.9.32.1-beta/src/ngx_pagespeed.cc:634: undefined reference to `net_instaweb::g_gzip_setter'
/home/temp/lnmp1.0/nginx-1.7.5/../ngx_pagespeed-release-1.9.32.1-beta/src/ngx_pagespeed.cc:634: undefined reference to `net_instaweb::NgxGZipSetter::SetGZipForLocation(ngx_conf_s*, bool)'
collect2: ld returned 1 exit status
```

and it's my configure

```
./configure --user=www --group=www --add-module=../ngx_pagespeed-release-1.9.32.1-beta --prefix=/usr/local/nginx --with-pcre --with-http_spdy_module --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-mail --with-mail_ssl_module --with-ipv6
```

It works on 1.8.31.4
