### ISSUE TITLE
Unable to compile with GCC 4.8

### ISSUE THREAD

**Issue by eleshar** [pagespeed/ngx_pagespeed#433]
Hi,

I'm attempting to install the latest release as outlined on https://developers.google.com/speed/pagespeed/module/build_ngx_pagespeed_from_source but my installation keeps failing with:

In file included from /root/sources/ngx_pagespeed/psol/include/third_party/chromium/src/base/logging.h:14:0,
                 from /root/sources/ngx_pagespeed/src/log_message_handler.cc:30:
/root/sources/ngx_pagespeed/psol/include/third_party/chromium/src/base/basictypes.h: In function âDest bit_cast(const Source&)â:
/root/sources/ngx_pagespeed/psol/include/third_party/chromium/src/base/basictypes.h:318:16: error: typedef âVerifySizesAreEqualâ locally defined but not used [-Werror=unused-local-typedefs]
   typedef char VerifySizesAreEqual [sizeof(Dest) == sizeof(Source) ? 1 : -1];
                ^
cc1plus: all warnings being treated as errors
make[1]: **\* [objs/addon/src/log_message_handler.o] Error 1
make[1]: Leaving directory `/root/sources/nginx-1.5.2'
make: **\* [install] Error 2

I'm on Ubuntu 13.04 and building with:
./configure   --prefix=/opt/nginx  --conf-path=/etc/nginx/nginx.conf   --pid-path=/var/run/nginx.pid   --lock-path=/var/lock/nginx.lock   --http-log-path=/var/log/nginx/access.log   --error-log-path=/var/log/nginx/error.log   --http-client-body-temp-path=/var/lib/nginx/body   --http-proxy-temp-path=/var/lib/nginx/proxy   --http-fastcgi-temp-path=/var/lib/nginx/fastcgi   --http-uwsgi-temp-path=/var/lib/nginx/uwsgi   --http-scgi-temp-path=/var/lib/nginx/scgi   --with-http_stub_status_module   --with-http_ssl_module   --with-http_realip_module   --with-http_gzip_static_module   --user=www-data   --group=www-data   --with-debug   --without-mail_pop3_module   --without-mail_imap_module    --without-mail_smtp_module  --add-module=/root/sources/ngx_pagespeed-release-1.6.29.3-beta --with-http_spdy_module
