### ISSUE TITLE
ngx_base_fetch.h:134:58: error: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [-Werror]

### ISSUE THREAD

**Issue by centminmod** [pagespeed/ngx_pagespeed#1248]
Only seem to be getting this with CentOS 6.x with GCC 4.9.1 servers while CentOS 7.x works fine with GCC 4.8.5

configure

> ./configure --with-ld-opt="-ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib" --with-cc-opt="-m64 -mtune=native -mfpmath=sse -DTCP_FASTOPEN=23 -g -O3 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2" --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --with-http_stub_status_module --with-http_secure_link_module --add-module=../nginx-module-vts --with-libatomic --with-threads --with-stream=dynamic --with-stream_ssl_module --with-http_gzip_static_module --add-dynamic-module=../ngx_brotli --add-dynamic-module=../ngx_pagespeed-release-1.11.33.3-beta --with-http_sub_module --with-http_addition_module --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-stream_geoip_module=dynamic --with-http_realip_module --add-dynamic-module=../ngx-fancyindex-0.4.0 --add-module=../ngx_cache_purge-2.3 --add-module=../ngx_devel_kit-0.3.0 --add-module=../set-misc-nginx-module-0.30 --add-module=../echo-nginx-module-0.59 --add-module=../redis2-nginx-module-0.13 --add-module=../ngx_http_redis-0.3.7 --add-module=../memc-nginx-module-0.17 --add-module=../srcache-nginx-module-0.31 --add-module=../headers-more-nginx-module-0.30 --with-pcre=../pcre-8.39 --with-pcre-jit --with-http_ssl_module --with-http_v2_module --with-openssl=..    /openssl-1.0.2h

error

    make -f objs/Makefile install
    make[1]: Entering directory `/svr-setup/nginx-1.11.3'
    ccache gcc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -m64 -mtune=native -mfpmath=sse -DTCP_FASTOPEN=23 -g -O3 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -DNDK_SET_VAR -DNDK_UPSTREAM_LIST -Wno-write-strings  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-c++11-extensions -I src/core -I src/event -I src/event/modules -I src/os/unix -I ../ngx_devel_kit-0.3.0/objs -I objs/addon/ndk -I ../ngx_pagespeed-release-1.11.33.3-beta/psol/include -I ../ngx_pagespeed-release-1.11.33.3-beta/psol/include/third_party/chromium/src -I ../ngx_pagespeed-release-1.11.33.3-beta/psol/include/third_party/google-sparsehash/src -I ../ngx_pagespeed-release-1.11.33.3-beta/psol/include/third_party/google-sparsehash/gen/arch/linux/x64/include -I ../ngx_pagespeed-release-1.11.33.3-beta/psol/include/third_party/protobuf/src -I ../ngx_pagespeed-release-1.11.33.3-beta/psol/include/third_party/re2/src -I ../ngx_pagespeed-release-1.11.33.3-beta/psol/include/out/Release/obj/gen -I ../ngx_pagespeed-release-1.11.33.3-beta/psol/include/out/Release/obj/gen/protoc_out/instaweb -I ../ngx_pagespeed-release-1.11.33.3-beta/psol/include/third_party/apr/src/include -I ../ngx_pagespeed-release-1.11.33.3-beta/psol/include/third_party/aprutil/src/include -I ../ngx_pagespeed-release-1.11.33.3-beta/psol/include/third_party/apr/gen/arch/linux/x64/include -I ../ngx_pagespeed-release-1.11.33.3-beta/psol/include/third_party/aprutil/gen/arch/linux/x64/include -I ../pcre-8.39 -I ../openssl-1.0.2h/.openssl/include -I objs -I src/http -I src/http/modules -I src/http/v2 -I ../ngx_devel_kit-0.3.0/src -I ../ngx_devel_kit-0.    3.0/src -I ../ngx_devel_kit-0.3.0/objs -I objs/addon/ndk -I src/stream \
                    -o objs/addon/src/ngx_base_fetch.o \
                    ../ngx_pagespeed-release-1.11.33.3-beta/src/ngx_base_fetch.cc
    In file included from ../ngx_pagespeed-release-1.11.33.3-beta/src/ngx_base_fetch.cc:23:0:
    ../ngx_pagespeed-release-1.11.33.3-beta/src/ngx_base_fetch.h:134:58: error: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [-Werror]
       bool IsCachedResultValid(const ResponseHeaders& headers) override;
                                                              ^
    cc1plus: error: unrecognized command line option "-Wno-c++11-extensions" [-Werror]
    cc1plus: all warnings being treated as errors
    make[1]: *** [objs/addon/src/ngx_base_fetch.o] Error 1
    make[1]: Leaving directory `/svr-setup/nginx-1.11.3'
    make: *** [install] Error 2

configure excerpt

    ./configure --with-ld-opt="-ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib" --with-cc-opt="-m64 -mtune=native -mfpmath=sse -DTCP_FASTOPEN=23 -g -O3 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2" --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --with-http_stub_status_module --with-http_secure_link_module --add-module=../nginx-module-vts --with-libatomic --with-threads --with-stream=dynamic --with-stream_ssl_module --with-http_gzip_static_module --add-dynamic-module=../ngx_brotli --add-dynamic-module=../ngx_pagespeed-release-1.11.33.3-beta --with-http_sub_module --with-http_addition_module --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-stream_geoip_module=dynamic --with-http_realip_module --add-dynamic-module=../ngx-fancyindex-0.4.0 --add-module=../ngx_cache_purge-2.3 --add-module=../ngx_devel_kit-0.3.0 --add-module=../set-misc-nginx-module-0.30 --add-module=../echo-nginx-module-0.59 --add-module=../redis2-nginx-module-0.13 --add-module=../ngx_http_redis-0.3.7 --add-module=../memc-nginx-module-0.17 --add-module=../srcache-nginx-module-0.31 --add-module=../headers-more-nginx-module-0.30 --with-pcre=../pcre-8.39 --with-pcre-jit --with-http_ssl_module --with-http_v2_module --with-openssl=..    /openssl-1.0.2h
    checking for OS
     + Linux 4.5.5-x86_64-linode69 x86_64
    checking for C compiler ... found
     + using GNU C compiler
     + gcc version: 4.9.1 20140922 (Red Hat 4.9.1-10) (GCC) 
    checking for gcc -pipe switch ... found
    checking for --with-ld-opt="-ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib" ... found
    checking for -Wl,-E switch ... found
    checking for gcc builtin atomic operations ... found
    checking for C99 variadic macros ... found
    checking for gcc variadic macros ... found
    checking for gcc builtin 64 bit byteswap ... found

more details at https://gist.github.com/centminmod/9ab52330b57e5fe9886af7e32abb4575

**Comment by centminmod** [comment]
with `cc1plus: error: unrecognized command line option "-Wno-c++11-extensions" [-Werror]`

seems it's being introduced by ngx_pagespeed at https://github.com/pagespeed/ngx_pagespeed/blob/46bc8ac06513236759252827ed44ddcc1aa5174b/config#L290

**Comment by crowell** [comment]
@centminmod can you try this patch?

```diff
diff --git a/src/ngx_base_fetch.h b/src/ngx_base_fetch.h
index 77409df..8717557 100644
--- a/src/ngx_base_fetch.h
+++ b/src/ngx_base_fetch.h
@@ -131,7 +131,7 @@ class NgxBaseFetch : public AsyncFetch {
   ngx_http_request_t* request() { return request_; }
   NgxBaseFetchType base_fetch_type() { return base_fetch_type_; }
 
-  bool IsCachedResultValid(const ResponseHeaders& headers) override;
+  virtual bool IsCachedResultValid(const ResponseHeaders& headers);
 
  private:
   virtual bool HandleWrite(const StringPiece& sp, MessageHandler* handler);
```

**Comment by morlovich** [comment]
That shouldn't be needed.

https://github.com/pagespeed/ngx_pagespeed/blob/46bc8ac06513236759252827ed44ddcc1aa5174b/config.make
is supposed to add -std=c++11

**Comment by morlovich** [comment]
Oh, right, the line above:
# config.make is not executed for dynamic modules
CFLAGS="$CFLAGS -Wno-c++11-extensions"

... Wonder why this has a different PoV on whether we're using c++11...

**Comment by centminmod** [comment]
@crowell the patch did work, but it's not needed and a bug on ngx_pagespeed end ?

working config on CentOS 6.8 64bit OS server

> nginx -V
> nginx version: nginx/1.11.3
> built by gcc 4.9.1 20140922 (Red Hat 4.9.1-10) (GCC) 
> built with LibreSSL 2.4.2
> TLS SNI support enabled
> configure arguments: --with-ld-opt='-lrt -ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib' --with-cc-opt='-m64 -mtune=native -mfpmath=sse -DTCP_FASTOPEN=23 -g -O3 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2' --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --with-http_stub_status_module --with-http_secure_link_module --add-module=../nginx-module-vts --with-libatomic --with-threads --with-stream=dynamic --with-stream_ssl_module --with-http_gzip_static_module --add-dynamic-module=../ngx_brotli --add-dynamic-module=../ngx_pagespeed-release-1.11.33.3-beta --with-http_sub_module --with-http_addition_module --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-stream_geoip_module=dynamic --with-http_realip_module --add-dynamic-module=../ngx-fancyindex-0.4.0 --add-module=../ngx_cache_purge-2.3 --add-module=../ngx_devel_kit-0.3.0 --add-module=../set-misc-nginx-module-0.30 --add-module=../echo-nginx-module-0.59 --add-module=../redis2-nginx-module-0.13 --add-module=../ngx_http_redis-0.3.7 --add-module=../memc-nginx-module-0.17 --add-module=../srcache-nginx-module-0.31 --add-module=../headers-more-nginx-module-0.30 --with-pcre=../pcre-8.39 --with-pcre-jit --with-http_ssl_module --with-http_v2_module --with-openssl=../libressl-2.4.2

**Comment by yusn** [comment]
In file included from /root/ngx_pagespeed-release-1.11.33.3-beta/src/ngx_base_fetch.cc:23:0:
/root/ngx_pagespeed-release-1.11.33.3-beta/src/ngx_base_fetch.h:134:58: error: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [-Werror]
   bool IsCachedResultValid(const ResponseHeaders& headers) override;

**Comment by yusn** [comment]
Debian 8 64bit

> 
In file included from /root/ngx_pagespeed-release-1.11.33.3-beta/src/ngx_base_fetch.cc:23:0:
/root/ngx_pagespeed-release-1.11.33.3-beta/src/ngx_base_fetch.h:134:58: error: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [-Werror]
   bool IsCachedResultValid(const ResponseHeaders& headers) override;
>

**Comment by Negaihoshi** [comment]
ubuntu 16.04 got the same problem.
```
In file included from /home/ubuntu/ngx_pagespeed-1.11.33.3-beta/src/ngx_base_fetch.cc:23:0:
/home/ubuntu/ngx_pagespeed-1.11.33.3-beta/src/ngx_base_fetch.h:134:58: error: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [-Werror]
   bool IsCachedResultValid(const ResponseHeaders& headers) override;
                                                          ^
cc1plus: all warnings being treated as errors
objs/Makefile:1780: recipe for target 'objs/addon/src/ngx_base_fetch.o' failed
make[3]: *** [objs/addon/src/ngx_base_fetch.o] Error 1
make[3]: Leaving directory '/home/ubuntu/nginx/nginx-1.11.3'
Makefile:8: recipe for target 'build' failed
make[2]: *** [build] Error 2
make[2]: Leaving directory '/home/ubuntu/nginx/nginx-1.11.3'
dh_auto_build: make -j1 returned exit code 2
debian/rules:70: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 2
make[1]: Leaving directory '/home/ubuntu/nginx/nginx-1.11.3'
debian/rules:62: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

**Comment by joustava** [comment]
@Negaihoshi and @yusn if you apply the patch @centminmod posted above the build will at least 
go through.

**Comment by crowell** [comment]
i've updated the tag to include the latest change removing c++11 code from `ngx_base_fetch` please redownload if you were building as dynamic module.

**Comment by centminmod** [comment]
thanks @crowell worked perfectly :)

**Comment by hillsp** [comment]
Out of interest, what version of nginx are you building? One of our team found something in the nginx repo that we think ought to have solved the problem:

http://hg.nginx.org/nginx/rev/35487ea55cb6

**Comment by Negaihoshi** [comment]
@joustava Thanks, it's work on Ubuntu 16.04.

**Comment by centminmod** [comment]
@hillsp question directed at who ? i use nginx 1.11.3

**Comment by hillsp** [comment]
Thanks @centminmod. You should have that commit, so something else must be going on. We'll make sure this gets fixed on trunk before the next release.
