### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Angristan** [pagespeed/ngx_pagespeed#1117]
Hello,

I have this error when compiling Nginx 1.9.11 + PageSpeed 1.10.33.4 on Debian 8 :

```
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -D_GLIBCXX_USE_CXX11_ABI=0  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /opt/nginx/ngx_pagespeed-release-1.10.33.4-beta/psol/include -I /opt/nginx/ngx_pagespeed-release-1.10.33.4-beta/psol/include/third_party/chromium/src -I /opt/nginx/ngx_pagespeed-release-1.10.33.4-beta/psol/include/third_party/google-sparsehash/src -I /opt/nginx/ngx_pagespeed-release-1.10.33.4-beta/psol/include/third_party/google-sparsehash/gen/arch/linux/x64/include -I /opt/nginx/ngx_pagespeed-release-1.10.33.4-beta/psol/include/third_party/protobuf/src -I /opt/nginx/ngx_pagespeed-release-1.10.33.4-beta/psol/include/third_party/re2/src -I /opt/nginx/ngx_pagespeed-release-1.10.33.4-beta/psol/include/out/Release/obj/gen -I /opt/nginx/ngx_pagespeed-release-1.10.33.4-beta/psol/include/out/Release/obj/gen/protoc_out/instaweb -I /opt/nginx/ngx_pagespeed-release-1.10.33.4-beta/psol/include/third_party/apr/src/include -I /opt/nginx/ngx_pagespeed-release-1.10.33.4-beta/psol/include/third_party/aprutil/src/include -I /opt/nginx/ngx_pagespeed-release-1.10.33.4-beta/psol/include/third_party/apr/gen/arch/linux/x64/include -I /opt/nginx/ngx_pagespeed-release-1.10.33.4-beta/psol/include/third_party/aprutil/gen/arch/linux/x64/include -I /opt/libressl/libressl-2.3.2/.openssl/include -I objs -I src/http -I src/http/modules -I src/http/v2 -I src/mail -I src/stream \
        -o objs/addon/src/ngx_pagespeed.o \
        /opt/nginx/ngx_pagespeed-release-1.10.33.4-beta/src/ngx_pagespeed.cc
/opt/nginx/ngx_pagespeed-release-1.10.33.4-beta/src/ngx_pagespeed.cc:3133:1: error: deprecated conversion from string constant to ‘char*’ [-Werror=write-strings]
 };
 ^
/opt/nginx/ngx_pagespeed-release-1.10.33.4-beta/src/ngx_pagespeed.cc:3148:1: error: deprecated conversion from string constant to ‘char*’ [-Werror=write-strings]
 };
 ^
cc1plus: all warnings being treated as errors
objs/Makefile:1743: recipe for target 'objs/addon/src/ngx_pagespeed.o' failed
make[1]: *** [objs/addon/src/ngx_pagespeed.o] Error 1
make[1]: Leaving directory '/opt/nginx/src/nginx-1.9.11'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by jeffkaufman** [comment]
Sorry about that!  PageSpeed needs a patch before it will work with nginx 1.9.11.  For now you could use nginx 1.9.10, or you could wait for our 1.10.33.5 release which will fix this incompatibility.  (Right now I'm expecting 1.10.33.5 will be out on Tuesday.)

**Comment by Angristan** [comment]
Glad to know that :) Thanks !

**Comment by nikolay** [comment]
@jeffkaufman Great!

**Comment by team4music** [comment]
Thanks for the info

**Comment by yusn** [comment]
@Angristan now 1.10.33.5 is released

**Comment by oschaaf** [comment]
The release may be near to completion, but I have not seen any announcement yet for 1.10.33.5 at https://groups.google.com/forum/#!forum/ngx-pagespeed-announce

**Comment by Angristan** [comment]
It works with 1.9.11 now :D

**Comment by aceslup** [comment]
Hi @jeffkaufman，gcc4.4，nginx1.9.11/12，PageSpeed1.9.32.13，Compilation Error。
This is part of the error：
configuring additional modules
adding module in /usr/local/src/ngx_pagespeed-1.9.32.13-beta
mod_pagespeed_dir=/usr/local/src/ngx_pagespeed-1.9.32.13-beta/psol/include
build_from_source=false
checking for psol ... found
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
If i don't want to change the GCC version，Can solve?

**Comment by crowell** [comment]
@aceslup can you paste the whole error log from objs/error.log to gist.github.com and paste the link here?
